"deploy": {
  "runtime": "v2",
  "numReplicas": 1,
  "startCommand": "bash -c 'prisma generate && uvicorn app.main:app --host 0.0.0.0 --port ${PORT}'",
  "sleepApplication": false,
  "useLegacyStacker": false
}
